PREFIX iot-lite: <http://purl.oclc.org/NET/UNIS/fiware/iot-lite#>
PREFIX m3-lite: <http://purl.org/iot/vocab/m3-lite#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX geo:  <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dul: <http://www.loa.istc.cnr.it/ontologies/DUL.owl#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX sics: <http://smart-ics.ee.surrey.ac.uk/fiesta-iot#>

SELECT  ?sensingDevice ?dataValue ?dateTime
WHERE {
?observation ssn:observedBy ?sensingDevice .
VALUES ?sensingDevice { 
<http://smart-ics.ee.surrey.ac.uk/fiesta-iot/resource/sc-sics-sp-001-power> 
<http://smart-ics.ee.surrey.ac.uk/fiesta-iot/resource/sc-sics-sp-002-power>
} .
?observation ssn:observationResult ?sensorOutput .
?sensorOutput ssn:hasValue ?obsValue .
?obsValue dul:hasDataValue ?dataValue .
?observation ssn:observationSamplingTime ?instant .
?instant time:inXSDDateTime ?dateTime .
  FILTER ( 
       ( xsd:dateTime(?dateTime) > xsd:dateTime("2017-05-05T14:10:00Z"))
    && ( xsd:dateTime(?dateTime) < xsd:dateTime("2017-05-05T14:20:00Z"))
    ) .
}ORDER BY ?sensingDevice ASC(?dateTime)   

# timezone might affect result if the reading is not in that format