PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ssn: <http://www.w3.org/2005/Incubator/ssn/ssnx/ssn#>
prefix qu-rec20: <http://purl.org/NET/ssnx/qu/qu-rec20#>
prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix iot-lite: <http://purl.oclc.org/NET/UNIS/fiware/iot-lite#>
prefix iot-l-Ins: <http://purl.oclc.org/NET/UNIS/fiware/iot-liteInstance#>

SELECT ?sensDev ?endp
WHERE {
    ?sensDev iot-lite:hasQuantityKind qu-rec20:temperature;
    iot-lite:isExposedBy ?serv;
    iot-lite:hasCoverage ?cover.
    ?cover iot-lite:hasPoint ?point.
    ?point iot-lite:RelativeLocation "Desk2".
    ?serv iot-lite:endpoint ?endp.	
}
#order by asc(UCASE(str(?s)))